### ISSUE TITLE
Our Group Book Exchange Club features

### ISSUE THREAD

**Issue by Ellacancode** [Ellacancode/CITS5505Project_Book-Excahnge-Club#1]
After our meeting,  we identified our main features as:

1. User register, and log in.
2. User Profile
3. Forum for users' book discussion
5. Bookshelf for checking book status
6. Search Functions for discussion

**Comment by LongQin0121** [comment]
I was just wondering maybe I can add  a password reset function? It is  cool, but gonna   take a while to complete it.

**Comment by Yunwei-Zhang** [comment]
looks good, but seems that we also need an intro/home page, describing the context and purpose of app and also allow user to create account or login

**Comment by lucychen0305** [comment]
For the forum user book function, maybe we can let users comment pictures as well with their comments

**Comment by Ellacancode** [comment]
Thanks everyone for the constructive feedback, we will consider all in our further development

**Comment by Ellacancode** [comment]
all features complete
