### ISSUE TITLE
Found Bug when Register

### ISSUE THREAD

**Issue by Ellacancode** [Ellacancode/CITS5505Project_Book-Excahnge-Club#11]
<img width="1509" alt="Screenshot 2024-05-14 at 4 09 49 PM" src="https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/130945383/74aa827d-49f7-48a3-ade8-fe7f17556eb7">
Just found that people can register with random email, and can set password with only 1 digit, which is problematic and cause security issue in the future.

**Here is the code snippet that need to fix ASAP:**
in forms.py
# Form for user registration
class RegistrationForm(FlaskForm):
    username = StringField('Username',validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

    # Custom validator to ensure username is not already in use
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Sorry, the username is unavailable , please choose another one')
    
    # Custom validator to ensure email is not already in use
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Sorry, the email is unavailable , Please choose a different one.')

**You may also need to change the routes!**

**Comment by LongQin0121** [comment]
Thanks Ella, I have   noticed this  problem,  we need to come out with  an solution  to refine it.  Come back to you later.

**Comment by LongQin0121** [comment]
I have    fixed the Bug,  please   check it out:
## Modify the Registration Form to Add New Validation Rules

```python
class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[
        DataRequired(), 
        Length(min=2, max=20)
    ])
    email = StringField('Email', validators=[
        DataRequired(),
        Email(),
        Regexp(r'^[\w\.-]+@(qq\.com|outlook\.com|gmail\.com)$', message="Email must be a valid email")
    ])
    password = PasswordField('Password', validators=[
        DataRequired(),
        Length(min=6, max=12, message="Password must be between 6 and 12 characters")
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(),
        EqualTo('password', message='Passwords must match')
    ])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Sorry, the username is unavailable, please choose another one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Sorry, the email is unavailable, please choose a different one.')

**Comment by lucychen0305** [comment]
I dont think we should limit the email because there are so many different emails, e.g. @yahoo.com, @hotmail.com, there are some we havent even heard. But i do agree with the password needing to be restricted.

**Comment by LongQin0121** [comment]
> I dont think we should limit the email because there are so many different emails, e.g. @yahoo.com, @hotmail.com, there are some we havent even heard. But i do agree with the password needing to be restricted.

That  also make sense, we need to think twice~

**Comment by LongQin0121** [comment]
Maybe We  need to enhance the password complexity, such as Uppercase ,lowercase or special characters~

**Comment by Ellacancode** [comment]
Advice taken! Here is the new version, where Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character and not limit on email service provider.

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, Regexp
from Bookclub.models import User
import re

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=15)])  # Username length between 2 and 15
    email = StringField('Email', validators=[
        DataRequired(),
        Email()
    ])
    password = PasswordField('Password', validators=[
        DataRequired(),
        Length(min=8, message="Password must be at least 8 characters"),
        Regexp(
            r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]',
            message="Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character"
        )
    ])
    confirm_password = PasswordField('Confirm Password', validators=[
        DataRequired(),
        EqualTo('password', message='Passwords must match')
    ])
    submit = SubmitField('Sign Up')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Sorry, the username is unavailable, please choose another one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Sorry, the email is unavailable, please choose a different one.')
