### ISSUE TITLE
Blueprint issues.

### ISSUE THREAD

**Issue by LongQin0121** [Ellacancode/CITS5505Project_Book-Excahnge-Club#12]
![1715675302268](https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/128503853/1682b3a7-83a3-4dce-9fd7-92619e6d9db9)
Right now, I have  created a blueprint branch  which will    completely change the files structure.
It is going to be challenging！

**Comment by Ellacancode** [comment]
Don't worry about it Long! I studied the lecture slides (the  testing one) and now I know how to implement blueprint, we actually don't need to change the whole file structure. Instead, we just need to add blueprint in our routes, change the routes a bit, and the url_for part. Lastly register the blueprint in the __init.py. Done! Not a big deal! I will do that!
<img width="1358" alt="Screenshot 2024-05-14 at 4 29 25 PM" src="https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/130945383/21f6a3d1-1e6c-4488-a146-f5724ceb8600">
<img width="1209" alt="Screenshot 2024-05-14 at 4 29 38 PM" src="https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/130945383/6371e281-cf91-4f62-86cf-48e8b357cb62">

<img width="1209" alt="Screenshot 2024-05-14 at 4 29 43 PM" src="https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/130945383/8584e51b-b2f4-4312-9c55-ef2f43ac58f0">

**Comment by Yunwei-Zhang** [comment]
looks good, but I am a bit worried is it too hard to merge code into blueprint format, if you need any help, just call our help. Hope can get it done on time!

**Comment by lucychen0305** [comment]
I think we should definitely change it to blue print, as thats part of the requirement. I can help with the merging and changing as well.
