### ISSUE TITLE
Not Enough JavaScript

### ISSUE THREAD

**Issue by LongQin0121** [Ellacancode/CITS5505Project_Book-Excahnge-Club#13]
Right now ,   most of the JavaScript code are inside the html.
![615c1c512670c071d878046a20caa6f](https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/128503853/5b82e653-9e79-4027-8d89-3f9e007178b2)

**Comment by lucychen0305** [comment]
I have commited some .js files, i will try to add more.

**Comment by Ellacancode** [comment]
Solved by Andy! He added javascript for our homepage, layout, profile, and shelf
