### ISSUE TITLE
Front end bug

### ISSUE THREAD

**Issue by lucychen0305** [Ellacancode/CITS5505Project_Book-Excahnge-Club#16]
I realised that you can't click the explore page from the book shelf for some reason. :( 

the code 
{% extends "layout.html" %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='shelf.css') }}">
{% endblock %}

{% block content %}
<header>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='shelf.js') }}"></script>
</header>
<div class="shelf-tit">
    <p>BOOK SHELF</p>
</div>

<br/>
<form action="{{ url_for('search_books') }}" method="post" class="shelf-searchbox">
    <p style="display: inline-block; width: 10%; font-weight: bold;">Book Name</p>
    <input type="hidden" name="search_by" value="book_title" style="display: inline-block;">
    <input type="text" name="query" placeholder="Search for books..." class="shelf-searcher">
    <button type="submit" class="shelf-btn">Search</button>
</form>
{% if results %}
    <ul>
    {% for book in results %}
        <li>{{ book.name }} by {{ book.author }} - {{ book.genre }}</li>
    {% endfor %}
    </ul>
{% endif %}

<div class="shelf-container">
    <div class="row">
    {% for book in books %}
      <div class="col-md-3 col-cub">
        <div class="shelf-book">
            <button 
                type="button" 
                class="btn btn-info btn-lg" 
                data-toggle="modal" 
                data-target="#myModal" 
                data-book-id="{{ book.id }}" 
                data-book-title="{{book.title}}"
                data-book-author="{{ book.author }}" 
                data-book-isbn="{{ book.isbn }}" 
                data-book-genre="{{ book.genre }}" 
                data-book-status="{{ book.status }}" 
                style="width: 100%; height: 100%; background-color: rgba(255, 255, 255, 0); border: hidden;">
                <img src="../static/shelf_pics/default.png" style="width: 100%; height: 90%; border-radius: 25px; z-index: 1;" class="shelf-img">
            </button>
            <p class="col-content">{{book.title}}</p>
            <form method="POST" action="{{ url_for('shelf') }}">
                <input type="hidden" name="book_id" value="{{ book.id }}">
                {% if book.status == "available" %}
                    <button type="submit" class="btn-borrow" id="btn-{{ book.id }}">Borrow</button>
                {% else %}
                    <p class="txt-unava" id="btn-{{ book.id }}">Not Available</p>
                {% endif %}
            </form>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
        
  <div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <p id="modal-id"></p>
                <p id="modal-tit"></p>
                <p id="modal-aut"></p>
                <p id="modal-isbn"></p>
                <p id="modal-gen"></p>
                <p id="modal-sta"></p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

**Comment by Ellacancode** [comment]
I just checked. Here is the fix, just simply remove this line.

Because you already inherent from the layout HTML, it will stuck if you do that again:<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>

**Comment by lucychen0305** [comment]
thank you, its solved now
