### ISSUE TITLE
missing intro pages

### ISSUE THREAD

**Issue by Yunwei-Zhang** [Ellacancode/CITS5505Project_Book-Excahnge-Club#17]
everything works well in home pages, with many new sections added, but seems to be missing the introduction section in home, better add one in next sprint, so that new users will not be confused

Please review and give some feedbacks, thanks.

![image](https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/62420557/bba7e5d8-d49b-4021-b9c5-d688df0ffa47)

**Comment by LongQin0121** [comment]
OK , now we need to work on it ..

**Comment by Ellacancode** [comment]
Thank you Lucy and Andy for adding the intro view of the homepage
![Screenshot 2024-05-15 at 10 24 51 PM](https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/130945383/1db30548-3dae-4ea2-b3b9-aee39d123f3f)
![Screenshot 2024-05-15 at 10 25 01 PM](https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/130945383/04a50e00-694f-439a-9d5f-d372521c9f6a)
![Screenshot 2024-05-15 at 10 25 23 PM](https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/130945383/0c7085f6-b607-484c-b2f1-884b22280498)
