### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Yunwei-Zhang** [Ellacancode/CITS5505Project_Book-Excahnge-Club#3]
Hey, I have found the following bugs in current projects:

1. In login/register pages, the main layout does not match the header-navigation, which means in different screen size, the perfermance are totally different (maybe issues in css that use 'px' instead of '%' or 'vh/vw').
2. the post search can just only search content, but not available for searching users
3. activating virtual environment may have issues in computers (one does not work for me in my PC)
4. register/login submit and back buttons have delays that may not response at first click
5. the rest are good!

**Comment by LongQin0121** [comment]
Right now ,the  blueprint is working ,not bot all of them,  the new post  and   single post  can not be connected, especially, when  I am trying to upload the image ,the app  crashes.  I think it is  related to the uploade_images funtion: 
`
#     return picture_fn
def upload_images(form_picture, storage_path, output_size=(125, 125)):
    # Generate a unique file name
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext

    # Determine the path to save the image
  _picture_path = os.path.join(bp.root_path, storage_path, picture_fn)_

    # Open the image and create a thumbnail
    i = Image.open(form_picture)
    i.thumbnail(output_size)  # Resize the image using the provided output_size
    i.save(picture_path)

    return picture_fn
`     
The picture path would be wrong ,if we change to blueprint.  Need to be fixwed!

**Comment by Ellacancode** [comment]
Fix the post search issue!  I modify the route.py
# Create search function 
@main.route('/search', methods=["GET", "POST"])
def search():
    form = SearchForm()
    posts = Post.query
    comments = Comment.query
    if form.validate_on_submit():
        search_term = form.searched.data
        # Perform filtering using OR to search across multiple fields
        posts = posts.join(User).outerjoin(Comment).filter(
            (Post.title.ilike(f'%{search_term}%')) | #search by post title
            (Post.content.ilike(f'%{search_term}%')) | #search by post content
            (User.username.ilike(f'%{search_term}%')) | #search by username
            (Comment.content.ilike(f'%{search_term}%')) #search by comment content
        ).order_by(Post.date_posted.desc()).all()

        return render_template("search.html",
                               form=form,
                               searched=search_term,
                               posts=posts)
    return render_template("search.html",
                           form=form,
                           searched='',
                           posts=[])

for now all bugs fixed. Next time let's post sepreate issue for bug!
