### ISSUE TITLE
New functionality: retrieve password via email

### ISSUE THREAD

**Issue by Ellacancode** [Ellacancode/CITS5505Project_Book-Excahnge-Club#32]
We need to increase our project complexity. In real life, people may forgot their password, so we need to provide them a function to reset the password.

Here is the tutorial 
https://blog.miguelgrinberg.com/post/the-flask-mega-tutorial-part-x-email-support

Can you please add that function ASAP? thank you

**Comment by LongQin0121** [comment]
let  us learn this tutorial first before we do it

**Comment by lucychen0305** [comment]
Hi, I have learnt how to do it, its all done :)
