### ISSUE TITLE
DO  we  need a password reset function?

### ISSUE THREAD

**Issue by LongQin0121** [Ellacancode/CITS5505Project_Book-Excahnge-Club#36]
DO  we  need a password reset function?

**Comment by Ellacancode** [comment]
If we have time, we can do that! However, the method of using email to retrieve the password is a bit complicated. If we do that, we also need a new password reset HTML. So what you guys think?

**Comment by lucychen0305** [comment]
Hi guys, i think we do need a retrieve password function, i have completed the backend and done the html. Its all solved :)
