### ISSUE TITLE
issue id registration page

### ISSUE THREAD

**Issue by Yunwei-Zhang** [Ellacancode/CITS5505Project_Book-Excahnge-Club#37]
the first time I type password, everything works well, but once I try to retype the password, it seems to miss the 'eye' icon to view my password.

![image](https://github.com/Ellacancode/CITS5505Project_Book-Excahnge-Club/assets/62420557/ff845534-dc59-461e-a9c3-d81ef0a0216a)

**Comment by Ellacancode** [comment]
Fixed!
