### ISSUE TITLE
Front End Issues

### ISSUE THREAD

**Issue by lucychen0305** [Ellacancode/CITS5505Project_Book-Excahnge-Club#9]
1. Footer not the the bottom of the page 
2. Buttons not matching
3. User profile page needs to be changed

**Comment by LongQin0121** [comment]
The  main page has  two side scroll bar, which is not good looking~

**Comment by Yunwei-Zhang** [comment]
Thanks Ella for these issues, I have almost fixed all these bugs and will be pushed into develop branch soon, then you can have a review and check the function again!

**Comment by Ellacancode** [comment]
Thank you Andy and Lucy!
